version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  usermanagementapi:
    build:
      context: .
      dockerfile: UserManagement.API/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGODB_CONNECTIONSTRING=mongodb://root:UserDb@mongodb:27017
    ports:
      - "5000:80"
    depends_on:
      - rabbitmq
      - mongodb
